### ISSUE TITLE
Source/documentation missing for input file

### ISSUE THREAD

**Issue by isosceleswheel** [pch-code/circ-scripts#1]
Hello,

I am trying to run the scripts contained in this repo as described [here](https://www.sciencedirect.com/science/article/pii/S2666166721004755#undfig1). When I come to the line 

```
perl GetExonsAndFlankingIntronsRegionsPerAnnotatedCircRNA.pl -i Rattus_norvegicus.Rnor_6.0.96.MergedExonsByGene.txt -c circRNA.5reads.1ind.annotated -o circRNAExonicCoords.txt
``` 

I am not able to find a source in your documentation for the file `circRNA.5reads.1ind.annotated`. I do find a file with the same name in the folder `/starchip/example/STARChip-circRNA/ExpectedOutput` in the `starchip` [repo](https://github.com/LosicLab/starchip), but it is unclear if this is the file that is being referred to in your code example because there is no reference to the file in the documentation. 

Can you please clarify the source for the file referred to in your code?

Thanks!
-David

**Comment by pch-code** [comment]
Hi David,

Yes, this file is created by STARChip-circRNA.

Regards,
Philippe

**Comment by isosceleswheel** [comment]
I see. And is this file sample specific or general for all circular RNA analysis? The call to that file appears to be in the middle of a set of database construction steps and there is no `{sample id}` in the file path so I assume it is a general database file but it is not immediately clear from the `starchip` documentation. 

Thanks!
-David

**Comment by pch-code** [comment]
The file is based on the entire analysis (not specific to just one sample).
